repos:
  - repo: local
    hooks:
      - id: fmt
        name: cargo fmt
        description: format files with "cargo fmt"
        types:
          - rust
        language: system
        entry: cargo fmt
        args:
          - --
