repos:
  - repo: https://github.com/backplane/pre-commit-rust-hooks
    rev: v1.1.0
    hooks:
    -   id: fmt
    -   id: check
    -   id: clippy
  - repo: https://github.com/fsfe/reuse-tool
    rev: v4.0.3
    hooks:
      - id: reuse
