# SPDX-License-Identifier: MIT OR Apache-2.0
version = 1

[[annotations]]
path = ["**/*.md"]
SPDX-FileCopyrightText = "2024-2025 University of Rochester"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["src/**/*.rs", "Cargo.toml", ".pre-commit-config.yaml", "**/REUSE.toml", "*.yaml", "tests/**/*.rs", "examples/**/*.rs", "BUILD.gn"]
SPDX-FileCopyrightText = "2024-2025 University of Rochester"
SPDX-License-Identifier = "MIT OR Apache-2.0"


# The following have no copyright and are licensed under CC0-1.0
[[annotations]]
path = ["rust-toolchain.toml", ".rustfmt.toml", "Cargo.lock"]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "None"
