# SPDX-License-Identifier: MIT OR Apache-2.0
version = 1

[[annotations]]
path = ["src/**/*.rs", "Cargo.toml", "Cargo.lock", ".pre-commit-config.yaml", "REUSE.toml", "*.yaml"]
SPDX-FileCopyrightText = "2024 University of Rochester"
SPDX-License-Identifier = "MIT OR Apache-2.0"
