# SPDX-License-Identifier: MIT OR Apache-2.0
version = 1

[[annotations]]
path = ["abc_*.hpp"]
SPDX-FileCopyrightText = "2024-2025 University of Rochester"
SPDX-License-Identifier = "MIT OR Apache-2.0"